# Generated by Django 5.1.7 on 2025-04-29 07:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('theater', '0003_seats'),
    ]

    operations = [
        migrations.AlterField(
            model_name='showtimes',
            name='screen_number',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
